"""Add system_prompt column

Revision ID: 2576c4594769
Revises: 001
Create Date: 2026-02-24 00:28:15.895751
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2576c4594769'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompts_unserved', table_name='prompts', postgresql_where='(is_served = false)')
    op.create_index(op.f('ix_prompts_is_served'), 'prompts', ['is_served'], unique=False)
    op.drop_index('idx_serve_log_prompt', table_name='serve_log')
    op.drop_index('idx_serve_log_time', table_name='serve_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_serve_log_time', 'serve_log', ['served_at'], unique=False)
    op.create_index('idx_serve_log_prompt', 'serve_log', ['prompt_id'], unique=False)
    op.drop_index(op.f('ix_prompts_is_served'), table_name='prompts')
    op.create_index('idx_prompts_unserved', 'prompts', ['id'], unique=False, postgresql_where='(is_served = false)')
    # ### end Alembic commands ###
